config/routes.rb
Photogur::Application.routes.draw do
  root :to => 'pictures#index'

  resources :pictures

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	attr_accessible :title, :artist, :url, :copyrighted

    validates :title, :presence => true
    validates :url, { 
        :format => {
            :with => /^https?:/, :message => "Please Enter a Valid URL"
        }
    }

    scope :alphabetical, order("title ASC")
    scope :free, where(:copyrighted => false)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	# before_filter :load_pictures

	def index
		@pictures = Picture.all
		if params[:free] == 'yes'
			@pictures = Picture.free.all
		else 
			@pictures = Picture.alphabetical.all
		end
	end

	def show
		@picture = Picture.find params[:id]
	end

	def new
		@picture = Picture.new
		@picture.title = "Enter Title"
	end

	def create
		@picture = Picture.new(params[:picture])
		if @picture.save
			redirect_to pictures_path
		else 
			flash[:error] = "Could not save the picture. Please try again."
			render :new
		end
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])
		if @picture.update_attributes params[:picture]
			redirect_to @picture
		else
			redirect_to pictures_path
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>   
    <div class="nav">
        <ul>
            <li><%= link_to "Pictures", pictures_path %> </li>
            <li><%= link_to "New", new_picture_path %> </li>
        </ul>
    </div>
    <%= yield %>
</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
    <div class="error"><%= flash[:error] %></div>
    <p>
        <%= f.label "title", "Enter Image Title"  %><br>
        <%= @picture.errors[:title].join(",") %>
        <%= f.text_field "title" %></label>
    </p>
    <p>
        <%= f.label "artist", "Enter Artist Name" %><br>
        <%= f.text_field "artist"%></label>
    </p>
    <p>
        <%= f.label "url", "Enter Image URL" %><br>
        <%= @picture.errors[:url].join(",") %>
        <%= f.text_field "url" %>
    </p>
    <p>
        <%= f.check_box "copyrighted" %>
        <%= f.label "copyrighted", "Photo has a copyright?" %>
    </p>
    <p>
        <%= f.submit "Save"  %>
    </p>
<% end %>

app/views/pictures/edit.html.erb
<H1>Edit <%= @picture.title %></H1>

<%= render :partial => "form" %>

app/views/pictures/index.html.erb
<%= link_to "Free pictures only", pictures_path(:free => "yes") %>

<h1>Photogur!</h1>

<%= link_to "New Picture", new_picture_path %>

<%- @pictures.each do |picture| %>
	<div class = 'picture'>
		<h2><%=picture.title%></h2>
		<h3><%=picture.artist%></h3>
        
		<%= link_to picture_path picture do %>
            <%= image_tag picture.url  %>
        <% end %>

		<%= button_to "Edit", picture_path(picture), :method => :get %>
        <br>
		<hr>
	</div>
<% end %>

app/views/pictures/new.html.erb
<h1>Add an Image!</h1>

<%= render :partial => "form" %>

app/views/pictures/show.html.erb
<h1><%= @picture.title %></h1>
<img src= "<%= @picture.url %>"></img>
<%= link_to "Edit", edit_picture_path(@picture) %>
<%= link_to "Delete", @picture , :method => :delete, :confirm => "Are you sure you want to delete this picture?" %>
<% if @picture.copyrighted %>
    <p>This image is protected.</p>
<% end %>
<h2><%= @picture.artist %></h2>